Repository Lempac/Oxy, pull requests merged in 2024-10, with the labels that each got.

#12 Updated lock files.
  .env.example
  composer.lock
  devenv.lock
  devenv.nix
  package-lock.json
  phpunit.xml
  tests/Feature/ExampleTest.php
  tests/Unit/ExampleTest.php
Labels: enhancement

#16 Add routes for home
  app/Http/Controllers/Auth/AuthenticatedSessionController.php
  app/Http/Controllers/Auth/ConfirmablePasswordController.php
  app/Http/Controllers/Auth/EmailVerificationNotificationController.php
  app/Http/Controllers/Auth/EmailVerificationPromptController.php
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/Auth/VerifyEmailController.php
  app/Http/Controllers/HomeController.php
  app/Http/Middleware/HandleInertiaRequests.php
  app/Http/Requests/Auth/LoginRequest.php
  config/database.php
  config/mail.php
  database/migrations/2024_09_06_100403_create_servers_table.php
  resources/js/Layouts/AuthenticatedLayout.vue
  resources/js/Pages/Home.vue
  resources/js/Pages/Welcome.vue
  resources/js/Pages/settings/Role.vue
  resources/js/Pages/settings/Server.vue
  resources/js/types/index.d.ts
  routes/web.php
  tests/Feature/Auth/AuthenticationTest.php
  tests/Feature/Auth/EmailVerificationTest.php
  tests/Feature/Auth/RegistrationTest.php
Labels: enhancement

#18 Fixed stuff with frontend
  composer.lock
  package-lock.json
  resources/js/Components/ServerSelectBar.vue
  resources/js/Pages/Settings/Role.vue
  resources/js/Pages/Settings/Server.vue
  routes/web.php
Labels: bug, dependencies

#20 Fixed and add stuff
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/HomeController.php
  database/migrations/0001_01_01_000000_create_users_table.php
  devenv.nix
  resources/js/Layouts/AuthenticatedLayout.vue
  resources/js/Pages/Home.vue
  resources/js/Pages/Welcome.vue
  resources/js/types/index.d.ts
Labels: bug, enhancement

#21 Updated seeder
  database/seeders/DatabaseSeeder.php
Labels: enhancement

#23 Fixed home page problems
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Layouts/AuthenticatedLayout.vue
  resources/js/Pages/Home.vue
Labels: bug, enhancement

#22 Updated settings (no css style I promise :3)
  resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
  resources/js/Pages/Settings/Role.vue
  resources/js/Pages/Settings/Server.vue
Labels: enhancement

#24 Fix stuff with backend
  app/Http/Controllers/HomeController.php
  composer.lock
  devenv.lock
  devenv.nix
  package-lock.json
  resources/js/Components/ServerSelectBar.vue
  resources/js/Layouts/AuthenticatedLayout.vue
Labels: bug, enhancement

#26 Artis
  app/Console/Commands/SendMessageCommand.php
  app/Events/test.php
  app/Http/Controllers/ServerController.php
  app/Models/User.php
  composer.json
  composer.lock
  resources/js/Pages/Welcome.vue
  resources/js/app.ts
  resources/js/bootstrap.ts
  resources/js/echo.ts
  resources/js/types/global.d.ts
  resources/js/ziggy.ts
  resources/views/app.blade.php
  routes/channels.php
  routes/web.php
  tests/Feature/Auth/ServerControllerTest.php
Labels: enhancement

#25 removed useless components
  composer.lock
  devenv.lock
  package-lock.json
  resources/js/Components/Checkbox.vue
  resources/js/Components/DangerButton.vue
  resources/js/Components/Dropdown.vue
  resources/js/Components/DropdownLink.vue
  resources/js/Components/ErrorAlert.vue
  resources/js/Components/InputError.vue
  resources/js/Components/InputLabel.vue
  resources/js/Components/Modal.vue
  resources/js/Components/NavLink.vue
  resources/js/Components/PrimaryButton.vue
  resources/js/Components/ResponsiveNavLink.vue
  resources/js/Components/SecondaryButton.vue
  resources/js/Components/TextInput.vue
  resources/js/Pages/Auth/ConfirmPassword.vue
  resources/js/Pages/Auth/ForgotPassword.vue
  resources/js/Pages/Auth/ResetPassword.vue
  resources/js/Pages/Auth/VerifyEmail.vue
  resources/js/Pages/Profile/Partials/DeleteUserForm.vue
  resources/js/Pages/Profile/Partials/UpdatePasswordForm.vue
  resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
  tailwind.config.js
Labels: enhancement

#27 Updated routes
  app/Enums/ChannelType.php
  app/Http/Controllers/HomeController.php
  app/Models/Channel.php
  bootstrap/app.php
  config/sanctum.php
  database/migrations/2024_10_16_140050_create_personal_access_tokens_table.php
  routes/api.php
  routes/web.php
  tests/Feature/Auth/ServerControllerTest.php
Labels: bug, enhancement

#28 Fixed home controller
  app/Http/Controllers/HomeController.php
  routes/web.php
Labels: bug

#29 home routing
  app/Http/Controllers/HomeController.php
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Layouts/AuthenticatedLayout.vue
  resources/js/Pages/Text/Messaging.vue
  resources/js/Pages/Text/Texting.vue
  resources/js/types/index.d.ts
  routes/web.php
Labels: enhancement

#30 Rewrote and expanded
  resources/js/Pages/Welcome.vue
  tests/Feature/HomeTest.php
Labels: enhancement

#31 Server creation (now you can make servers)
  app/Http/Controllers/ServerController.php
  resources/js/Components/ServerSelectBar.vue
  resources/js/app.ts
  resources/js/types/global.d.ts
  resources/js/types/index.d.ts
  routes/api.php
  routes/web.php
  tests/Feature/Auth/ServerControllerTest.php
Labels: enhancement

#32 Add the sender to message
  app/Http/Controllers/HomeController.php
  app/Http/Middleware/HandleInertiaRequests.php
  resources/js/types/global.d.ts
  resources/js/types/index.d.ts
  tsconfig.json
Labels: enhancement

#33 Add files
  .env.example
  app/Enums/MessageType.php
  app/Http/Controllers/HomeController.php
  app/Http/Controllers/ProfileController.php
  app/Http/Controllers/ServerController.php
  app/Http/Requests/ProfileUpdateRequest.php
  app/Models/Message.php
  app/Models/User.php
  composer.lock
  package-lock.json
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Layouts/AuthenticatedLayout.vue
  resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
  resources/js/Pages/Welcome.vue
  resources/js/app.ts
  resources/js/bootstrap.ts
  resources/js/echo.ts
  resources/js/ssr.ts
  resources/js/types/global.d.ts
  resources/js/types/index.d.ts
  routes/web.php
  storage/framework/cache/.gitignore
  storage/framework/cache/data/.gitignore
  tests/Feature/Auth/ServerControllerTest.php
  tests/Feature/ProfileTest.php
Labels: enhancement

#34 Add message receiving and server editing
  .github/workflows/laravel.yml
  .gitignore
  app/Console/Commands/SendMessageCommand.php
  app/Events/Message.php
  app/Events/test.php
  app/Http/Controllers/Api/ServerController.php
  app/Http/Controllers/Auth/AuthenticatedSessionController.php
  app/Models/User.php
  bootstrap/app.php
  database/factories/MessageFactory.php
  devenv.lock
  package-lock.json
  package.json
  resources/js/Components/ServerSelectBar.vue
  resources/js/Layouts/AuthenticatedLayout.vue
  routes/api.php
  routes/web.php
  tailwind.config.js
  tests/Feature/Auth/ServerControllerTest.php
Labels: enhancement

#37 Made changes to events and controllers
  app/Console/Commands/SendMessageCommand.php
  app/Events/Channels/ChannelCreated.php
  app/Events/Channels/ChannelDeleted.php
  app/Events/Channels/ChannelEdited.php
  app/Events/Message.php
  app/Events/Messages/MessageCreated.php
  app/Events/Messages/MessageDeleted.php
  app/Events/Messages/MessageEdited.php
  app/Events/Servers/ServerCreated.php
  app/Events/Servers/ServerEdited.php
  app/Events/Servers/ServerJoined.php
  app/Events/Servers/ServerLeft.php
  app/Http/Controllers/Api/ChannelController.php
  app/Http/Controllers/Api/MessageController.php
  app/Http/Controllers/Api/ServerController.php
  app/Http/Controllers/Auth/NewPasswordController.php
  app/Providers/AppServiceProvider.php
  bootstrap/app.php
  database/factories/ChannelFactory.php
  database/factories/MessageFactory.php
  database/migrations/2024_09_06_110527_create_channels_table.php
  database/migrations/2024_09_06_140704_create_messages_table.php
  routes/api.php
  routes/web.php
  tests/Feature/Api/ChannelControllerTest.php
  tests/Feature/Api/MessageControllerTest.php
  tests/Feature/Api/ServerControllerTest.php
Labels: enhancement

#38 messaging and text channel create
  app/Http/Controllers/Api/MessageController.php
  app/Http/Controllers/HomeController.php
  app/Models/Message.php
  database/factories/MessageFactory.php
  database/migrations/2024_09_06_140704_create_messages_table.php
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Pages/Text/Texting.vue
  resources/js/types/index.d.ts
  routes/api.php
  vite.config.js
Labels: enhancement

#39 Add simple broadcast for chat, Joining, Settings icon
  .env.example
  app/Events/Messages/MessageCreated.php
  app/Events/Messages/MessageDeleted.php
  app/Events/Servers/ServerCreated.php
  app/Events/Servers/ServerEdited.php
  app/Events/Servers/ServerJoined.php
  app/Events/Servers/ServerLeft.php
  app/Http/Controllers/Api/ServerController.php
  app/Http/Controllers/HomeController.php
  app/Models/Message.php
  bootstrap/app.php
  config/hashing.php
  devenv.nix
  package-lock.json
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Layouts/AuthenticatedLayout.vue
  resources/js/Pages/Home.vue
  resources/js/Pages/Settings/Role.vue
  resources/js/Pages/Settings/Server.vue
  resources/js/Pages/Settings/Settings.vue
  resources/js/Pages/Text/Texting.vue
  resources/js/Pages/Welcome.vue
  resources/js/bootstrap.ts
  resources/js/echo.ts
  resources/js/types/index.d.ts
  routes/api.php
  routes/channels.php
  routes/web.php
Labels: bug, enhancement

#41 Claps invite code
  resources/js/Layouts/AuthenticatedLayout.vue
Labels: enhancement

#42 Updated Home page (probably the 5th version)
  public/images/kanban.png
  public/images/message.jpg
  public/images/message.png
  public/images/messages.jpg
  public/images/oxy.png
  public/images/server.png
  public/images/servers.png
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Pages/Welcome.vue
  routes/web.php
Labels: enhancement

#43 Fixed events, Updated dependencies
  app/Events/Channels/ChannelEdited.php
  app/Events/Messages/MessageCreated.php
  app/Events/Messages/MessageDeleted.php
  app/Events/Messages/MessageEdited.php
  app/Events/Servers/ServerCreated.php
  app/Events/Servers/ServerEdited.php
  composer.lock
  package-lock.json
  resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
  resources/js/Pages/Text/Texting.vue
Labels: enhancement

#44 Added roles Table
  .env.example
  app/Console/Commands/SendMessageCommand.php
  app/Models/Role.php
  app/Models/Server.php
  app/Models/User.php
  database/migrations/2024_09_06_16100_user_server.php
  database/migrations/2024_10_28_125920_create_roles_table.php
  database/migrations/2024_10_28_132809_role_server_user.php
Labels: enhancement

#45 Fixed channel deletion, Add server deletion
  app/Http/Controllers/Api/ServerController.php
  database/migrations/2024_09_06_130827_create_calls_table.php
  database/migrations/2024_09_06_140704_create_messages_table.php
  routes/api.php
Labels: bug, enhancement

#46 Fixed texting and added a couple of buttons
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Components/MembersList.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Layouts/AuthenticatedLayout.vue
  resources/js/Pages/Text/Texting.vue
Labels: enhancement

#47 Added roles controller
  app/Events/Roles/RoleCreated.php
  app/Events/Roles/RoleDeleted.php
  app/Events/Roles/RoleEdited.php
  app/Http/Controllers/Api/RoleController.php
  app/Models/Role.php
  routes/api.php
  tests/Feature/Api/RoleControllerTest.php
Labels: enhancement

#49 Add users array in server
  .gitignore
  app/Http/Controllers/HomeController.php
  resources/js/types/index.d.ts
Labels: enhancement

#48 Server settings (ver1)
  app/Http/Controllers/Api/ServerController.php
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Pages/Settings/Server.vue
  resources/js/Pages/Welcome.vue
  routes/web.php
Labels: enhancement

#50 Added mail server, Fixed wrong path
  app/Http/Controllers/HomeController.php
  app/Models/User.php
  devenv.nix
Labels: bug, enhancement

#51 members list
  resources/js/Components/MembersList.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Layouts/AuthenticatedLayout.vue
  resources/js/Pages/Text/Texting.vue
Labels: enhancement
