Repository Lempac/Oxy, pull requests merged in 2024-11, with the labels that each got.

#52 Role settings 1.1
  app/Http/Controllers/Api/RoleController.php
  app/Http/Controllers/Api/ServerController.php
  artisan
  database/migrations/2024_10_28_125920_create_roles_table.php
  database/migrations/2024_10_28_132809_role_server_user.php
  resources/js/Components/ServerSelectBar.vue
  resources/js/Pages/Settings/Role.vue
  resources/js/Pages/Settings/Server.vue
  resources/js/Pages/Welcome.vue
  resources/js/types/index.d.ts
  routes/api.php
  routes/web.php
Labels: enhancement

#53 Updated factory, started work on roles
  .gitignore
  app/Enums/PermsType.php
  app/Http/Controllers/Api/RoleController.php
  app/Http/Controllers/Api/ServerController.php
  app/Models/Role.php
  composer.lock
  database/factories/MessageFactory.php
  database/migrations/2024_10_28_125920_create_roles_table.php
  devenv.nix
  devenv.yaml
  package-lock.json
  package.json
  resources/js/Pages/Settings/Server.vue
  resources/js/Pages/Text/Texting.vue
  resources/js/Pages/Welcome.vue
  resources/js/types/index.d.ts
Labels: enhancement

#54 File/image handling
  app/Http/Controllers/Api/MessageController.php
  composer.lock
Labels: enhancement

#56 New component
  composer.lock
  database/migrations/2024_09_06_110527_create_channels_table.php
  package-lock.json
  resources/js/Components/ConfirmDialog.vue
  resources/js/Pages/Settings/Server.vue
  resources/js/Pages/Welcome.vue
Labels: enhancement

#57 Small tweek
  resources/js/Components/ServerSelectBar.vue
Labels: enhancement

#58 Moved baseUrl to global, Made button change style on isDirty, Removed update color function.
  resources/js/Components/MembersList.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue
  resources/js/Pages/Settings/Role.vue
  resources/js/Pages/Settings/Server.vue
  resources/js/Pages/Settings/Settings.vue
  resources/js/Pages/Text/Texting.vue
  resources/js/bootstrap.ts
Labels: enhancement

#59 send files and images
  app/Http/Controllers/HomeController.php
  composer.lock
  devenv.lock
  package-lock.json
  resources/js/Components/ConfirmDialog.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Pages/Settings/Server.vue
  resources/js/Pages/Text/Texting.vue
  resources/js/Pages/Welcome.vue
  routes/web.php
Labels: enhancement

#60 Manual v1
  public/images/AddServer.png
  public/images/Channels.png
  public/images/CreateAccount.png
  public/images/CreateServer.png
  public/images/CreateText.png
  public/images/DeleteAccount.png
  public/images/DeleteChannel.png
  public/images/DeleteMessage.png
  public/images/DeleteServer.png
  public/images/EditMessage.png
  public/images/EditText.png
  public/images/JoinServer.png
  public/images/NewRole.png
  public/images/Profile info.png
  public/images/Profile.png
  public/images/Register.png
  public/images/RenameText.png
  public/images/Roles.png
  public/images/ServerCode.png
  public/images/Settings.png
  public/images/SettingsIcon.png
  public/images/TextChannel.png
  public/images/Texting.png
  public/images/ToRoles.png
  public/images/UpdatePassword.png
  public/images/VerifyEmail.png
  public/images/design.png
  public/images/server.png
  resources/js/Pages/Manual.vue
  resources/js/Pages/Welcome.vue
  routes/web.php
Labels: enhancement

#61 voice channel look
  app/Http/Controllers/HomeController.php
  composer.lock
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Pages/Text/Texting.vue
  resources/js/Pages/Voice/Speaking.vue
  routes/web.php
  tests/Feature/HomeTest.php
Labels: enhancement

#63 readme
  README.md
Labels: enhancement

#67 Error checks
  .github/workflows/laravel.yml
  resources/js/Components/ServerSelectBar.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Pages/Profile/Partials/DeleteUserForm.vue
  resources/js/Pages/Settings/Server.vue
  resources/js/Pages/Welcome.vue
Labels: enhancement

#66 problem fixes
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Components/ServerSelectBar.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Layouts/AuthenticatedLayout.vue
  resources/js/Pages/Text/Texting.vue
  resources/js/Pages/Voice/Speaking.vue
Labels: enhancement

#68 General fixes
  app/Events/Channels/ChannelCreated.php
  app/Events/Channels/ChannelDeleted.php
  app/Events/Channels/ChannelEdited.php
  app/Events/Messages/MessageDeleted.php
  app/Events/Roles/RoleDeleted.php
  app/Http/Controllers/Api/MessageController.php
  app/Http/Controllers/Api/ServerController.php
  composer.lock
  database/migrations/2024_09_06_140704_create_messages_table.php
  devenv.lock
  devenv.nix
  package-lock.json
  resources/js/Components/ServerSelectBar.vue
  resources/js/Components/TextSelectBar.vue
  resources/js/Layouts/AuthenticatedLayout.vue
  resources/js/Pages/Home.vue
  resources/js/Pages/Text/Texting.vue
  resources/js/bootstrap.ts
Labels: bug, enhancement

#65 Kanban
  app/Http/Controllers/KanbanBoardController.php
  app/Http/Controllers/KanbanColumnController.php
  app/Http/Controllers/KanbanTaskController.php
  app/Models/KanbanBoard.php
  app/Models/KanbanColumn.php
  app/Models/KanbanTask.php
  composer.lock
  database/migrations/2024_10_17_060826_create_kanban_tables.php
  package-lock.json
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Pages/Kanban/Board.vue
  resources/js/Pages/Kanban/CreateBoard.vue
  resources/js/Pages/Kanban/EditBoard.vue
  resources/js/Pages/Kanban/Index.vue
  resources/js/Pages/Kanban/KanbanBoard.vue
  routes/web.php
Labels: enhancement

#69 update lock/Fixed menus
  app/Http/Controllers/KanbanBoardController.php
  composer.lock
  devenv.lock
  package-lock.json
  package.json
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Pages/Kanban/CreateBoard.vue
  resources/js/Pages/Kanban/EditBoard.vue
  resources/js/Pages/Kanban/Index.vue
  resources/js/Pages/Kanban/KanbanBoard.vue
  resources/js/types/index.d.ts
Labels: bug

#70 Leave server + roles importance change
  app/Http/Controllers/Api/ServerController.php
  resources/js/Components/ChannelSelectBar.vue
  resources/js/Pages/Settings/Members.vue
  resources/js/Pages/Settings/Role.vue
  resources/js/Pages/Settings/Server.vue
  resources/js/Pages/Welcome.vue
  routes/api.php
Labels: enhancement
